steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/dalprojects/k8s/outercontainer:v1'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/dalprojects/k8s/outercontainer:v1'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        PROJECT=$$(gcloud config get-value core/project)
        gke-gcloud-auth-plugin --version
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials "cluster-1" --project "dalprojects" --zone "us-central1"
        kubectl apply -f K8s/persistentvolume.yaml
        kubectl apply -f K8s/persistentvolumeclaim.yaml
        kubectl apply -f K8s/deployment.yaml
        kubectl apply -f K8s/service.yaml

options:
  logging: CLOUD_LOGGING_ONLY

