apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: a3-pvc
spec:
  volumeName: a3-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  selector:
    matchLabels:
      name: a3-pv